version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Istanbul"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      changesets:
        patterns:
          - "@changesets/*"
      commitlint:
        patterns:
          - "@commitlint/*"
      eslint:
        patterns:
          - "@cspell/*"
          - "@eslint/*"
          - "@types/*"
          - "eslint"
          - "eslint-*"
          - "*-eslint"
          - "globals"
